# --- CONFIGURACIÓN DE REDIRECCIÓN FINAL Y ROBUSTA ---

# Regla 1: Redirección de Enlaces Cortos con Prefijo /r/
# Esta regla es súper específica y no tiene ambigüedades.
[[redirects]]
  # 'from' captura cualquier petición que empiece con /r/
  from = "/r/:short_code"
  
  # 'to' la reenvía a tu función de Supabase.
  to = "https://ifivanwkvtjoykpcjczc.supabase.co/functions/v1/redirect/:short_code"
  
  # 'status = 302' es una redirección temporal que le dice al navegador que cambie la URL.
  status = 302


# Regla 2: Regla "Catch-All" para tu aplicación de React (SPA).
# Esta regla se ejecuta para TODO LO DEMÁS.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200