[[redirects]]
from = "/:short_code"
to = "https://ifivanwkvtjoykpcjczc.supabase.co/functions/v1/redirect/:short_code"
status = 302

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "npm run build"
publish = "dist"