[[redirects]]
from = "/*"
to = "https://ifivanwkvtjoykpcjczc.supabase.co/functions/v1/redirect/:splat"
status = 302
force = true

[redirects.conditions]
Path = [ "^/(?!dashboard|login|signup|pricing|assets/).*$" ]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "npm run build"
publish = "dist"